main.exe instanciasPRPP\DEGREE\D0NoRPP 109
main.exe instanciasPRPP\DEGREE\D1NoRPP 115
main.exe instanciasPRPP\DEGREE\D2NoRPP 274
main.exe instanciasPRPP\DEGREE\D3NoRPP 172
main.exe instanciasPRPP\DEGREE\D4NoRPP 210
main.exe instanciasPRPP\DEGREE\D5NoRPP 313
main.exe instanciasPRPP\DEGREE\D6NoRPP 166
main.exe instanciasPRPP\DEGREE\D7NoRPP 260
main.exe instanciasPRPP\DEGREE\D8NoRPP 457
main.exe instanciasPRPP\DEGREE\D9NoRPP 160
main.exe instanciasPRPP\DEGREE\D10NoRPP 0
main.exe instanciasPRPP\DEGREE\D11NoRPP 398
main.exe instanciasPRPP\DEGREE\D12NoRPP 280
main.exe instanciasPRPP\DEGREE\D13NoRPP 717
main.exe instanciasPRPP\DEGREE\D14NoRPP 810
