main.exe instanciasPRPP\GRID\G0NoRPP 0
main.exe instanciasPRPP\GRID\G1NoRPP 0
main.exe instanciasPRPP\GRID\G2NoRPP 0
main.exe instanciasPRPP\GRID\G3NoRPP 2
main.exe instanciasPRPP\GRID\G4NoRPP 0
main.exe instanciasPRPP\GRID\G5NoRPP 4
main.exe instanciasPRPP\GRID\G6NoRPP 9
main.exe instanciasPRPP\GRID\G7NoRPP 1
main.exe instanciasPRPP\GRID\G8NoRPP 4
main.exe instanciasPRPP\GRID\G9NoRPP 2
main.exe instanciasPRPP\GRID\G10NoRPP 0
main.exe instanciasPRPP\GRID\G11NoRPP 4
main.exe instanciasPRPP\GRID\G12NoRPP 15
main.exe instanciasPRPP\GRID\G13NoRPP 11
main.exe instanciasPRPP\GRID\G14NoRPP 14
main.exe instanciasPRPP\GRID\G15NoRPP 26
